require('dotenv').config()
const productsRouter = require('./src/api/routes/cocacolaRoutes')
const { connectDB } = require('./src/config/db')
const express = require('express')
const app = express()
connectDB()
app.use(express.json())
app.use('/api/v1/cocacola', productsRouter)
app.use('*', (req, res, next) => res.status(404).json('route not foud'))
app.listen(3000, () => console.log('http://localhost:3000'))
